apiVersion : v1
kind: Deployment
metadata:
  name: discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery
  template:
    metadata:
      labels:
        app: discovery 
    spec:
      containers:
        - name: discovery 
          image: acrr11.azurecr.io/discoveryserver.git:#{Build.BuildId}#
          ports:
          - containerPort: 80